version: 2

# Sources
sources:
  - name: epl_analytics_dwh
    schema: epl_analytics_dwh
    tables:
      # Player Demographics Table
      - name: player_demo_data
        description: The raw dataset containing player information
        # Columns
        columns:
          - name: Player_Names
            description: Player full names
          - name: Club
            description: Player's current club
          - name: Nationality
            description: Player's nationality
          - name: Age
            description: Player's age
          - name: Position
            description: Player's position on the field
          - name: Prefered_Foot
            description: Player's preferred foot
          - name: Height
            description: Player's height
          - name: Weight
            description: Player's weight
          - name: Previous_Teams
            description: The previous teams player has played at
          - name: CreatedAt
            description: The date data was ingested
          - name: UpdatedAt
            description: The date data was updated
          - name: DOB
            description: The date player was born
          - name: Season
            description: League season


# Models
models:
  - name: stg__player_demographics
    description: Staging model with raw player information
    columns:
        - name: primary_key
          description: Surrogate primary key of table
        - name: player_names
          description: Player's full names
        - name: club
          description: Player's current club
        - name: nationality
          description: Player's nationality
        - name: age
          description: Player's age in years
        - name: playing_position
          description: Player's position on the field
        - name: prefered_playing_foot
          description: Player's prefered playing foot
        - name: height
          description: Player's height
        - name: height_units
          description: Heights unit of measure
        - name: weight
          description: Player's weight
        - name: weight_units
          description: Weights unit of measure
        - name: previous_teams
          description: Player's previous teams
        - name: date_of_birth
          description: Player's date of birth
        - name: season
          description: EPL Season
